services:
  artemis:
    image: apache/activemq-artemis:2.44.0
    user: root
    ports:
      - "61616:61616"
      - "61617:61617"
      - "8161:8161"
      - "1099:1099"
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    volumes:
      - ./artemis-data-244:/var/lib/artemis-instance/data
      #- ./broker.xml:/var/lib/artemis-instance/etc/broker.xml
    depends_on:
      - postgres
  postgres:
    image: postgres:18
    container_name: postgres-db-18
    environment:
      POSTGRES_DB: messages
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: alto
    ports:
      - "5432:5432"
    volumes:
      - ./pg-18:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    depends_on:
      - postgres
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
volumes:
  artemis-data-244:
  pg-18:
