services:
  artemis:
    image: apache/activemq-artemis:2.31.2
    user: root
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    volumes:
      - ./artemis-data:/var/lib/artemis-instance/data
      #- ./broker.xml:/var/lib/artemis-instance/etc/broker.xml
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: messages
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: alto
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  artemis-data:
  pg-data:
